[script]
start = "node index.js"

[[deployment]]
  name = "main"
  build = "npm install"
  start = "node index.js"
  
  [deployment.cron]
  schedule = "*/3 * * * *"  # Runs every 3 minutes
  timezone = "UTC"
