[script]
start = "node index.js"

[[deployment]]
  name = "main"
  build = "npm install"
  start = "node index.js"
  
  [deployment.cron]
  schedule = "*/20 * * * *"  # Runs every 20 minutes
  timezone = "UTC"
